//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by REGMON.RC
//
#define IDRESET                         3
#define IDM_EXIT                        104
#define IDM_SAMPLE                      105
#define IDM_ABOUT                       300
#define IDB_TOOLBAR                     400
#define ID_LIST                         1000
#define IDC_PROCFILTER                  1000
#define IDC_PATHFILTER                  1001
#define IDC_EXCLUDEFILTER               1002
#define IDC_HISTORY                     1003
#define IDC_PROCEXCLUDE                 1004
#define IDC_SUCCESS                     1006
#define IDC_ERROR                       1007
#define IDC_LOGREADS                    1008
#define IDC_LOGWRITES                   1009
#define IDC_DRIVE                       1050
#define IDM_SAVE                        40007
#define IDM_SAVEAS                      40012
#define IDM_ZEROSTATS                   40016
#define IDM_HELP                        40017
#define IDM_CAPTURE                     40018
#define IDM_AUTOSCROLL                  40019
#define IDM_CLEAR                       40020
#define IDM_FILTER                      40022
#define IDM_FIND                        40024
#define IDM_BOOTLOG                     40026
#define IDM_ONTOP                       40027
#define IDM_JUMP                        40028
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        123
#define _APS_NEXT_COMMAND_VALUE         40029
#define _APS_NEXT_CONTROL_VALUE         1011
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
